export enum StateType {
  // Arcade
  Idle = "Idle",
  IdleRotateLeft = "IdleRotateLeft",
  IdleRotateRight = "IdleRotateRight",
  StartWalkBackLeft = "StartWalkBackLeft",
  StartWalkBackRight = "StartWalkBackRight",
  StartWalkLeft = "StartWalkLeft",
  StartWalkRight = "StartWalkRight",
  StartWalkForward = "StartWalkForward",
  Walk = "Walk",
  EndWalk = "EndWalk",
  DropIdle = "DropIdle",
  DropRolling = "DropRolling",
  DropRunning = "DropRunning",
  Falling = "Falling",
  JumpIdle = "JumpIdle",
  JumpRunning = "JumpRunning",
  Sprint = "Sprint",
  // Vehicle
  CloseVehicleDoorInside = "CloseVehicleDoorInside",
  CloseVehicleDoorOutside = "CloseVehicleDoorOutside",
  Driving = "Driving",
  EnteringVehicle = "EnteringVehicle",
  ExitingVehicle = "ExitingVehicle",
  OpenVehicleDoor = "OpenVehicleDoor",
  Sitting = "Sitting",
  SwitchingSeats = "SwitchingSeats",
}
